darak:
  instance-name: DARAK_TEST
  domain: localhost
  jwt-secret: Y0ZhWVg4bllDa0VOQ2FIMzdRWHpCUFM2WHBHQ0p3bnFkc1JrTDU5VDdFOTJIOFhzWkc2NXFGd3VtaHZtN3dBZFBSSFpGbjhrUmZKeHpQNUhZWlFUTTNSMjN4VnU5ZlZLdEFnUm1VeUF6c1UzZXNnOHR3REhWS2VLYnNlN3VndG4=
  jwt-expiration-in-seconds: 3600
  port: 8080
  database:
    url: "172.30.1.6"
    username: darak_test
    password: ThisIsNotARealPassword
    port: 5432
    database: darak
  base-aes-key: RDwhLFY/X2U0aXFTNlY2IjglXWh5PzR7XV88b3E1SnM=
  share-error-to-developer: true
  send-default-pii: false
  base-directory: ./darak-data