spring:
  application:
    name: DarakServer
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
    show-sql: false
    generate-ddl: true

management:
  endpoints:
    jmx:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - refresh
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - refresh
      basePath: /acp
  endpoint:
    info:
      access: read_only
    health:
      access: read_only